### ISSUE TITLE
Duplicate Resources after image upload

### ISSUE THREAD

**Issue by NolanHill** [coyote-team/coyote-wp#75] opened 2020-11-23 21:17 UTC
1. Uploaded [image](https://chsdmdev.wpengine.com/wp-admin/upload.php?item=38556) to Media Library in WordPress 
2. "Manage image on Coyote website" Links to Coyote [resource](https://staging.coyote.pics/organizations/40/resources/316595)
3. Looking through [recently added resources](https://staging.coyote.pics/organizations/40/resources?q%5Bcanonical_id_or_name_or_representations_text_cont_all%5D=&q%5Bscope%5D%5B%5D=order_by_priority_and_date&q%5Bassignments_user_id_eq%5D=&q%5Bresource_group_resources_resource_group_id_in%5D=) in Coyote reveals that there are two versions of the resource. One version is for [http](https://staging.coyote.pics/organizations/40/resources/316595) and the other is for [https](https://staging.coyote.pics/organizations/40/resources/316596)
4. The media selector "Manage image on Coyote website" link takes you to the http version, but the alt text on the [page](https://chsdmdev.wpengine.com/example-willi-smith-page/) is drawn from the https version

**Comment by sinabahram** [comment] 2020-11-23 22:12
@jkva  can we use "//" instead of specific protocols? But, also looping in @flipsasser on this issue as Coyote should be potentially modified to do the same.

**Comment by flipsasser** [comment] 2020-11-23 22:43
I'll need to determine how many dupes this could potentially create in production before I make the change, but once I know I'll start stripping protocol off of resources as they're added

**Comment by jkva** [comment] 2020-12-02 13:50
Via https://github.com/coyote-team/coyote-wp/commit/c772d5e82a78529ca1f9620be12f425f1266b6ed any attachment url is now explicitly set to HTTPS. While I could strip off the protocol, it makes no sense for a WP installation to be running on a non-HTTPs connection.

**Comment by sinabahram** [comment] 2020-12-02 20:09
Understood, however isn't that just trading the problem, @jkva. It is why I was asking about // instead of http or https.

**Comment by jkva** [comment] 2020-12-02 21:37
There was more than one place in the code where attachment urls were loaded, this is now only done via a helper function which always maps to a `https://` url, which should prevent duplicate protocol image attachment urls from being used to create resources.

**Comment by sinabahram** [comment] 2020-12-02 22:28
Right, but what if the site is http only?

**Comment by jkva** [comment] 2020-12-03 17:14
Then the attachments won't resolve. The question is whether we should be encouraging WordPress installations that installed this plugin from not running SSL. Given most browsers already throw up a big warning I don't see the point. But if you're hard set on it I can strip the protocol.

**Comment by sinabahram** [comment] 2020-12-03 17:18
I hear you on SSL, but it is not that simple. Staging and other dev environments may not have SSL for folks. Even some of the top hosting sites don't seamlessly offer that on their dev pipelines, which is a problem.

So, that's why I'm asking about a protocol agnostic way. Why is it not possible to check for this and act appropriately?

**Comment by jkva** [comment] 2020-12-03 17:20
Fair point. Testing environments were my one case where I could consider a non-SSL connection. I'll make it protocol-agnostic.

**Comment by flipsasser** [comment] 2020-12-03 19:02
I have a change for that on my end as well, Job. It looks for resources
while ignoring the protocol.

**Comment by jkva** [comment] 2020-12-05 14:52
I've been testing with this, for instance over at https://staging.coyote.pics/organizations/43/resources/316674

Seems to work fine, the only thing I notice is that now the image is initially captioned (if without a caption) as `//coyote.pac.clients.3ode.nl/wp-content/uploads/2020/12/foo-bar-baz.jpeg`.

Other than that, no issue.

**Comment by jkva** [comment] 2020-12-05 14:53
It would also require any installations to import again, since this changes the `source_uri` for any attachment image already processed.

**Comment by sinabahram** [comment] 2020-12-05 17:19
hi @jkva  I don't understand your last two comments. Would you please explain further, illustrating with a few examples?

**Comment by jkva** [comment] 2020-12-05 17:24
The plugins tracks known resources via a hash calculated of the image's source. Since this source now has changed when dealing with attachments, any pre-existing hashes for those attachments will no longer be valid.

**Comment by sinabahram** [comment] 2020-12-05 17:32
That's only true of existing installations to date, though, right? You're not talking about something that will happen on fresh installations in the future? We don't have any actual installs of this plugin (which means that problem will never happen), so that's why I'm wondering about this comment and want to make sure I fully understand your point.

**Comment by jkva** [comment] 2020-12-05 17:34
Yes, that's correct. It's a technicality.

**Comment by jkva** [comment] 2020-12-05 17:35
As for the earlier comment, all that means is that before, if the resource wasn't created with an explicit title, it falls back to the source uri. Those now look a bit strange without the protocol in them, but again, probably not a big deal. I just didn't want to leave it out.

**Comment by sinabahram** [comment] 2020-12-05 18:10
I understand the above to be as follows. Please confirm.

1: If http changes to https, this will have zero effects what-so-ever on the plugin or the ability to look up images, etc.

2: The reverse of 1 is true with https turning into http

3: @flipsasser  propper protocol handlers will be added back in Coyote side, because otherwise we've just broken all the links.

4: @jkva  removing this protocol handler in no way adversely affects anything on fresh installs.

**Comment by jkva** [comment] 2020-12-05 18:34
I can confirm 1, 2, and 4.

**Comment by jkva** [comment] 2020-12-09 19:09
Closing as addressed plugin-side.

**Closed as completed by jkva** 2020-12-09 19:09 UTC
Labels: bug

**Comment by flipsasser** [comment] 2020-12-09 19:21
Cool - @Sina Bahram <sina@sinabahram.com> the answer is yes, we only
perform lookups for an upsert without protocol but the source URI remains
whatever we were initially given

**Comment by sinabahram** [comment] 2020-12-09 19:24
Amazing @flipsasser  thank you.
